Repository hassan-obeid/tr_b_causal_2020, pull requests merged in 2020-11, with the labels that each got.

#145 Tim self edits 3
  article/main.bib
  article/sections/_5_graph_testing.tex
Labels: documentation

#146 Add makefile targets for TB's part of project
  Makefile
  src/graphs/discovery.py
  src/workflow/store_discovery_graph.py
Labels: bug, enhancement

#147 Add black & flake8 pre-commit checks for notebooks
  .pre-commit-config.yaml
Labels: enhancement

#151 Tb self edits 4
  article/main.bib
  article/sections/_3_graph_overview.tex
  article/sections/_4_graph_construction.tex
  article/sections/_5_graph_testing.tex
  article/sections/_6_graph_discovery.tex
Labels: documentation

#153 Adding Eckles citation in mediator section
  article/main.bib
  article/sections/_4_graph_construction.tex
Labels: documentation

#157 Draft abstract section
  article/sections/_0_abstract.tex
  article/sections/_6_graph_discovery.tex
Labels: documentation

#155 Addressing Amine's comments
  article/main.bib
  article/sections/_6_graph_discovery.tex
Labels: documentation

#156 Experimental discovery section
  article/main.bib
  article/sections/_6_graph_discovery.tex
Labels: documentation

#154 Add discussion sec
  article/main.bib
  article/main.tex
  article/sections/_8_discussion.tex
  article/sections/_9_conclusion.tex
Labels: documentation

#158 adding Hassan's 3 sections
  article/sections/_1_intro_generic.tex
  article/sections/_3_graph_overview.tex
  article/sections/_7_latent_confounding.tex
Labels: documentation

#159 Adding section 2 latex files.
  article/sections/_2_graph_importance.tex
Labels: documentation

#160 Final notebook files amine
  notebooks/final/7.0-mab-selection-on-observables-final.ipynb
  notebooks/final/7.0-mab-selection-on-observables-final.md
  src/observables/__init__.py
  src/observables/availability.py
  src/observables/distfit.py
  src/observables/graphs.py
  src/observables/regression.py
  src/observables/simperturb.py
  src/observables/simulation.py
  src/observables/simworkflow.py
  src/observables/tests/__init__.py
  src/observables/tests/test_availability.py
  src/observables/tests/test_distfit.py
  src/observables/tests/test_regression.py
  src/observables/tests/test_simulation.py
  src/observables/utils.py
Labels: documentation
